import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '@/lib/fontawesome';
import './globals.css';
import { ReduxProvider } from '@/components/providers/ReduxProvider';
import { createClient } from '@/lib/supabase/server'; // Import the custom helper
import { RootState } from '@/lib/redux/store';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Use the custom createClient helper for server components
  const supabase = await createClient();

  const {
    data: { session },
  } = await supabase.auth.getSession();

  const initialState: RootState = {
    auth: {
      isAuthenticated: !!session,
      user: session?.user || null,
      status: 'idle',
      error: null,
    },
    // Initialize other slices if you have them
  };

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider initialState={initialState}>{children}</ReduxProvider>
      </body>
    </html>
  );
}
